DROP DATABASE IF EXISTS EmploiUs;
CREATE DATABASE EmploiUs;
USE EmploiUs;


CREATE TABLE T_ENTREPRISE_ENT(
    ENT_id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ENT_siret VARCHAR(256) NOT NULL,
    ENT_mail VARCHAR(256) NOT NULL,
    ENT_mdp VARCHAR(256) NOT NULL,
    ENT_domaine VARCHAR(256) NOT NULL
);

CREATE TABLE T_R_TYPEANNONCE_TYA(
    TYA_id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TYA_libelle VARCHAR(256)
);

CREATE TABLE T_ANNONCE_ANO(
    ANO_id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ANO_domaine VARCHAR(256) NOT NULL,
    ANO_date DATE NOT NULL,
    ANO_salaire INT(11),
    ANO_duree VARCHAR(256) NOT NULL,
    ANO_descriptif VARCHAR(256) NOT NULL,
    ANO_titre VARCHAR(256) NOT NULL,
    TYA_id INT(11) NOT NULL
);

CREATE TABLE T_CANDIDAT_CDT(
    CDT_id INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    CDT_nom VARCHAR(256) NOT NULL,
    CDT_prenom VARCHAR(256) NOT NULL,
    CDT_genre VARCHAR(1) NOT NULL,
    CDT_ddn DATE NOT NULL,
    CDT_adresse VARCHAR(256) NOT NULL,
    CDT_mail VARCHAR(256) NOT NULL,
    CDT_mdp VARCHAR(256) NOT NULL,
    CDT_tel INT(11),
    CDT_cv VARCHAR(256),
    ANO_id INT(11) NOT NULL
);

CREATE TABLE T_MESSAGE_MES(
    CDT_id INT(11) NOT NULL,
    ENT_id INT(11) NOT NULL,
    KEY CDT_id (CDT_id),
    KEY ENT_id (ENT_id),
    MES_date DATE NOT NULL,
    MES_contenu VARCHAR(256) NOT NULL,
    MES_titre VARCHAR(256) NOT NULL,
    PRIMARY KEY (CDT_id,ENT_id)
);

ALTER TABLE T_ANNONCE_ANO ADD CONSTRAINT FK_TYPEANNONCE FOREIGN KEY (TYA_id) REFERENCES T_R_TYPEANNONCE_TYA(TYA_id);
ALTER TABLE T_CANDIDAT_CDT ADD CONSTRAINT FK_ANNONCE FOREIGN KEY (ANO_id) REFERENCES T_ANNONCE_ANO(ANO_id);
ALTER TABLE T_MESSAGE_MES ADD CONSTRAINT FK_CANDIDAT FOREIGN KEY (CDT_id) REFERENCES T_CANDIDAT_CDT(CDT_id);
ALTER TABLE T_MESSAGE_MES ADD CONSTRAINT FK_ENTREPRISE FOREIGN KEY (ENT_id) REFERENCES T_ENTREPRISE_ENT(ENT_id);